default:
  Title: hand gesture regconigtion

development:
  keypoint_classifier: 
    # original
    # lable_path: model/keypoint_classifier/keypoint_classifier_label.csv
    # model_path: model/keypoint_classifier/keypoint_classifier.tflite
    # keypoint_csv_path: model/keypoint_classifier/keypoint.csv

    # miew's
    # label_path: model/keypoint_pinky_2class/keypoint_pinky_label.csv
    # model_path: model/keypoint_pinky_2class/keypoint_classifier_pinky_2class.tflite
    # keypoint_csv_path: model/keypoint_pinky_2class/keypoint_pinky.csv

    # nn tflite
    # label_path: model/keypoint_pinky_2class_miew/keypoint_pinky_label.csv
    # model_path: model/keypoint6mar/keypoint_classifier.tflite
    # model_type: tflite #tflite or sklearn
    # keypoint_csv_path: model/keypoint_pinky_2class_kk/kk_keypoint.csv

    # lrc sklearn
    label_path: model/keypoint_pinky_2class_miew/keypoint_pinky_label.csv
    model_path: model/keypoint6mar/keypoint_classifier_lrc_pipeline.pkl    
    model_type: sklearn #tflite or sklearn
    keypoint_csv_path: model/keypoint_pinky_2class_kk/kk_keypoint.csv
    

  point_history_classifier:
    label_path: model/point_history_classifier/point_history_classifier_label.csv
    model_path: model/point_history_classifier/point_history_classifier.tflite
    keypoint_csv_path: model/point_history_classifier/point_history.csv
    
  ground_truth:
    video_path: groundtruth/test_groundtruth.MOV
    output_path: groundtruth/ground_truth.csv
    gesture_names_path: model/keypoint_pinky_2class_miew/keypoint_pinky_label.csv
    frame_step: 30
  
  model_evaluation:
    video_path: groundtruth/test_groundtruth.MOV
    output_path: groundtruth/keypoint6mar_lrc_eval.csv
    gesture_names_path: model/keypoint_pinky_2class_miew/keypoint_pinky_label.csv
    frame_step: 30